name: Bug report
description: Report a reproducible problem in hdvec
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimal code to reproduce the issue
      render: python
    validations:
      required: true
  - type: input
    attributes:
      label: hdvec version
      description: Output of `python -c "import hdvec,sys;print(hdvec.__version__)"`
  - type: input
    attributes:
      label: Python version
  - type: input
    attributes:
      label: OS

