name: Feature request
description: Suggest an idea to improve hdvec
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Motivation
      description: What problem does this feature solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: Describe the desired API/behavior
  - type: textarea
    attributes:
      label: Alternatives
  - type: textarea
    attributes:
      label: Additional context

