name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pipx install uv
      - name: Install package (dev)
        run: uv pip install --system -e ".[dev]"
      - name: Lint
        run: |
          uv run ruff check .
          uv run black --check .
      - name: Type check
        run: uv run mypy .
      - name: Tests
        run: uv run pytest

  build-numba:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pipx install uv
      - name: Install package (dev + numba)
        run: uv pip install --system -e ".[dev,numba]"
      - name: Lint
        run: |
          uv run ruff check .
          uv run black --check .
      - name: Type check
        run: uv run mypy .
      - name: Tests
        run: uv run pytest
